### ISSUE TITLE
Erweiterung für Q.HOME+ ESS

### ISSUE THREAD

**Issue by fanatikz** [simatec/ioBroker.solax#101]
Hallo, 

wie realistisch wäre eine Erweiterung um die Q.HOME Cloud für die Qcells Hyb G3? Ist identisch zu Solax nur gebrandet und andere Web Adressen. 

Ich werde gerne auch unterstützen soweit ich kann, bin allerdings kein Softwareentwickler. 

Was ich bisher gesehen hab ist alles 1:1 identisch. 

Kann gerne weitere Infos beisteuern um Klarheit zu schaffen. 

Grüße fanatikz

**Comment by fanatikz** [comment]
Gerne, hier die Login Seite.
https://qhome-ess-g3.q-cells.eu/#/login?tokenStatus=true

Hier das json vom WiFi-Dongle(ohne Login)
Befehl: https://qhome-ess-g3.q-cells.eu/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=XXXXXXXXXXXXXXXXXXXXXXXX&sn=XXXXXXXXXX
Rückgabe:
{"success":true,"exception":"Query success!","result":{"inverterSN":"XXXXXXXXXXXXXX","sn":"XXXXXXXXXX","acpower":955.0,"yieldtoday":38.2,"yieldtotal":441.2,"feedinpower":60.0,"feedinenergy":270.68,"consumeenergy":37.79,"feedinpowerM2":0.0,"soc":73.0,"peps1":0.0,"peps2":0.0,"peps3":0.0,"inverterType":"14","inverterStatus":"102","uploadTime":"2022-06-06 21:27:32","batPower":-929.0,"powerdc1":0.0,"powerdc2":0.0,"powerdc3":null,"powerdc4":null}}

Und hier die Rückgabe vom InverterState nach Login:
(Das ist der Teil, der mich persönlich interessiert, die einfache Abfrage hab ich schon in Node Red, und teils schieb ich das in eine InfluxDB, Login, token-Rückgabe etc. ist für mich aber dann doch zu heftig ins Node Red zu bekommen, hab n bissl mit Postman gespielt, da klappt das auch)

https:// qhome-ess-g3.q-cells.eu/phoebus/inverterIndex/getInverterState

[
    {
        "inverterSn": "XXX",
        "wsn": "XXX",
        "moduleName": null,
        "userId": "XXX",
        "siteId": "XXX",
        "firmId": "XXX",
        "firmwareVer": null,
        "ratedPower": 15.0,
        "idc1": null,
        "idc2": null,
        "idc3": null,
        "idc4": null,
        "idc5": null,
        "idc6": null,
        "idc7": null,
        "idc8": null,
        "idc9": null,
        "idc10": null,
        "idc11": null,
        "idc12": null,
        "vdc1": null,
        "vdc2": null,
        "vdc3": null,
        "vdc4": null,
        "vdc5": null,
        "vdc6": null,
        "vdc7": null,
        "vdc8": null,
        "vdc9": null,
        "vdc10": null,
        "vdc11": null,
        "vdc12": null,
        "iac1": 1.0,
        "vac1": 233.0,
        "gridpower": 800.0,
        "temperature": 30.0,
        "todayyield": null,
        "yieldtoday": 0.0,
        "yieldtotal": 102.6,
        "feedinpower": 12.0,
        "powerdc1": 0.0,
        "powerdc2": 0.0,
        "powerdc3": null,
        "powerdc4": null,
        "powerdc5": null,
        "powerdc6": null,
        "powerdc7": null,
        "powerdc8": null,
        "powerdc9": null,
        "powerdc10": null,
        "powerdc11": null,
        "powerdc12": null,
        "pac1": 138.0,
        "pac2": 321.0,
        "pac3": 341.0,
        "iac2": 1.6,
        "iac3": 1.7,
        "vac2": 232.1,
        "vac3": 233.8,
        "fac1": 49.97,
        "fac2": 49.98,
        "fac3": 49.97,
        "feedinenergy": 122.77,
        "consumeenergy": 35.11,
        "uploadTime": 1653840089224,
        "uploadTimeValue": "2022-05-30 00:01:29",
        "type": null,
        "status": null,
        "version": "3.003.02",
        "inverterNum": null,
        "inverterTemperature": "42",
        "batVoltage1": 417.3,
        "batCurrent1": -1.7,
        "batPower1": -751.0,
        "temperBoard1": 27.0,
        "surplusEnergy1": 4.1,
        "inputEnergy1": 26.2,
        "outputEnergy1": 24.0,
        "batteryType": "1",
        "batteryStatus": "1",
        "batteryCapacity": 33.0,
        "chargecutVoltage": 467.2,
        "disChargecutVoltage": 320.0,
        "epsYieldToday": 0.0,
        "relay1Status": null,
        "relay1Power": null,
        "relay1Energy": null,
        "relay1Signal": null,
        "relay1answer": null,
        "relay2Status": null,
        "relay2Power": null,
        "relay2Energy": null,
        "relay2Signal": null,
        "relay2answer": null,
        "inverterStatus": 2.0,
        "inverterStatusValue": null,
        "systemSwitch": 1.0,
        "safety": null,
        "powerFactor": 1.0,
        "exportControl": null,
        "powerLimit": null,
        "inverterType": "14",
        "userName": "r.tagmann@gmail.com",
        "firmName": "浙江艾罗网络能源有限公司",
        "currentYieldIncome": null,
        "totalYieldIncome": null,
        "faultType": null,
        "wMachineStyle": null,
        "epsVoltageA": 0.0,
        "epsCurrentA": 0.0,
        "epsApowerActive": 0.0,
        "epsVoltageB": 0.0,
        "epsCurrentB": 0.0,
        "epsBpowerActive": 0.0,
        "epsVoltageC": 0.0,
        "epsCurrentC": 0.0,
        "epsCpowerActive": 0.0,
        "epsApowerS": 0.0,
        "epsBpowerS": 0.0,
        "epsCpowerS": 0.0,
        "feedinPowerMeter2": 0.0,
        "feedinEnergyMeter2": 0.0,
        "consumeEnergyMeter2": 0.0,
        "managerBootloaderVersion": "1.08",
        "seller": "1369634507158192130",
        "batteryBrand": "84",
        "batteryMasterVer": "3.05",
        "batterySlaveNum": "8",
        "batterySlaveVer1": null,
        "batterySlaveVer2": null,
        "batterySlaveVer3": null,
        "batterySlaveVer4": null,
        "batterySlaveVer5": null,
        "batterySlaveVer6": null,
        "batterySlaveVer7": null,
        "batterySlaveVer8": null,
        "batterySlaveVer9": null,
        "batterySlaveVer10": null,
        "batterySlaveVer11": null,
        "batterySlaveVer12": null,
        "batterySlaveVer13": null,
        "batterySlaveVer14": null,
        "batterySlaveVer15": null,
        "batterySlaveVer16": null,
        "batterySlaveType1": null,
        "batterySlaveType2": null,
        "batterySlaveType3": null,
        "batterySlaveType4": null,
        "batterySlaveType5": null,
        "batterySlaveType6": null,
        "batterySlaveType7": null,
        "batterySlaveType8": null,
        "batterySlaveType9": null,
        "batterySlaveType10": null,
        "batterySlaveType11": null,
        "batterySlaveType12": null,
        "batterySlaveType13": null,
        "batterySlaveType14": null,
        "batterySlaveType15": null,
        "batterySlaveType16": null,
        "iacL1N": null,
        "vacL1N": null,
        "iacL2N": null,
        "vacL2N": null,
        "genFreq": null,
        "genPower": null,
        "genL1Vol": null,
        "genL2Vol": null,
        "loadCurrentL1N": null,
        "loadCurrentL2N": null,
        "loadVoltL1N": null,
        "loadVoltL2N": null,
        "outputEnergy": null,
        "loadFlag": 0,
        "gridInputYieldTotal": 0.0,
        "batChargeYieldTotal": null,
        "pvYieldTotal": 102.8,
        "epsYieldTotal": 0.1,
        "vbatteryType": null,
        "dataReference": 0,
        "bmsBatVoltage": 416.1,
        "bmsBatCurrent": -1.7,
        "bmsBatPower": -707.0,
        "inverterMasterVer": "1.15",
        "inverterSlaveVer": "0.00",
        "managerVer": "1.14",
        "chargeVer": "0.00",
        "yieldIncr": 0.0,
        "feedinEnergyIncr": 0.0,
        "consumerEnergyIncr": 0.0,
        "consumerEnergyTmp": null,
        "feedinEnergyTmp": null,
        "selfUseIncome": 0.0,
        "feedIncome": 0.0,
        "consumerIncome": 0.0,
        "fiveMinuteVal": 0,
        "stateMessage1": null,
        "stateMessage2": null,
        "energyThroughout": 73670,
        "masterSN": "TP30AH717ID122",
        "slave1_2SN": null,
        "slave3_4SN": null,
        "slave5_6SN": null,
        "slave7_8SN": null,
        "slave9_10SN": null,
        "slave11_12SN": null,
        "slave13_14SN": null,
        "slave15_16SN": null,
        "isBatteryAlarm": 0,
        "isBatteryAlarmValue": null,
        "feedinpower1": null,
        "feedinpower2": null,
        "chargingRequset": 0,
        "voltageHighPackageNum": 2,
        "voltageHighCellNum": 7,
        "voltageLowPackageNum": 1,
        "voltageLowCellNum": 16,
        "tempHighPackageNum": 2,
        "tempHighCellNum": 5,
        "tempLowPackageNum": 4,
        "tempLowCellNum": 3,
        "dayTotalYield": null,
        "monthTotalYield": null,
        "yearTotalYield": null,
        "generationStatus": null,
        "batterySN": null,
        "siteName": "home",
        "leaseMode": 0,
        "lockMode": 0,
        "pvPower": 0.0,
        "powerdc": [
            0.0,
            0.0
        ],
        "vdc": [
            0.0,
            0.0
        ],
        "idc": [
            0.0,
            0.0
        ],
        "batterySlaveVer": [
            "3.07",
            "3.07",
            "3.07",
            "3.07",
            "3.07",
            "3.07",
            "3.07",
            "3.07",
            "0.00",
            "0.00",
            "0.00",
            "0.00",
            "0.00",
            "0.00",
            "0.00",
            "0.00"
        ],
        "batterySlaveType": [
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "14",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        "slaveSN": [
            "TP30BI106ID237",
            "TP30BI108ID258",
            "TP30BI106ID130",
            "TP30BI106ID210",
            "",
            "",
            "",
            ""
        ],
        "deviceAddress": null,
        "protocolTag": null,
        "producer": null,
        "model": null,
        "softwareVersion": null,
        "uploadSn": null,
        "protocolNo": null,
        "protocolVersion": null,
        "uab": null,
        "ubc": null,
        "uca": null,
        "reactivePower": null,
        "apparentPower": null,
        "reactiveYieldTotal": null,
        "reactiveYieldToday": null,
        "mpptNum": null,
        "pvModel": null,
        "busVoltage": 0.0,
        "dcPhaseA": null,
        "dcPhaseB": null,
        "dcPhaseC": null,
        "gfci": null,
        "subInverterStatus": null,
        "inverterTemperature2": null,
        "inverterTemperature3": null,
        "boostTemperature": null,
        "inductorTmperature": null,
        "insulationResistance": null,
        "fanState": null,
        "faultTime": null,
        "lastFaultType": null,
        "faultCode": null,
        "warningCode": null,
        "boostTemp1": null,
        "boostTemp2": null,
        "boostTemp3": null,
        "boostTemp4": null,
        "inverterTemp1": null,
        "inverterTemp2": null,
        "inverterTemp3": null,
        "acTemp1": null,
        "acTemp2": null,
        "acTemp3": null,
        "masterSlaveType": null,
        "inverterAddress": null,
        "runState": null,
        "gridL1Vol": null,
        "gridL1Cur": null,
        "gridL2Vol": null,
        "gridL2Cur": null,
        "gridFreq": null,
        "genL1Cur": null,
        "genL2Cur": null,
        "atsRunMode": null,
        "atsRunState": null,
        "atsErrorCode": null,
        "versionSlave": null,
        "versionMaster": null,
        "gridpriority": null,
        "manualpriority": null,
        "dischargeThroughput": null,
        "chargeThroughput": null,
        "tzMsg": null,
        "cbcMsg": null,
        "relayMsg": null,
        "pwrLimitMsg": null,
        "mpptCommType": null,
        "mpptMsg": null,
        "logData1": null,
        "logData2": null,
        "logData3": null,
        "logData4": null,
        "batteryCellVoltageHigh2": 3.258,
        "batteryCellVoltageLow2": 3.251,
        "batteryCellVoltageDValue": null,
        "bmslost": 0,
        "inverterError": 0.0,
        "epsvoltage": null,
        "epscurrent": null,
        "epsfrequency": 0.0,
        "bmsdisChargemaxCurrent": null,
        "batteryCellTemperatureHigh": 21.2,
        "batteryCellTemperatureLow": 18.9,
        "batteryCellVoltageHigh": 3.3,
        "batteryCellVoltageLow": 3.3,
        "batteryHealth": "2",
        "bmscommunication": null,
        "userChargemaxCurrent": 22.2,
        "userDischargemaxCurrent": 30.0,
        "workMode": null,
        "bmserror": 0.0,
        "managerRrror": 0.0,
        "epspower": 0.0,
        "minCapacity": null,
        "bmschargemaxCurrent": null,
        "meterFunction": null,
        "meter1ComState": 1.0,
        "meter2ComState": 0.0,
        "managerError": 0.0,
        "bmserror2": null
    },

**Comment by fuxx-consulting** [comment]
Hallo Simatec,

meine Qcells Anlage kommt im August. gibt es hierzu schon Infos die du uns geben kannst?

VG
Andreas

**Comment by simatec** [comment]
Denke bis dahin werde ich soweit sein

**Comment by fuxx-consulting** [comment]
Hallo, Simatec,

meine Anlage steht und geht am Montag final an das Netz, falls du jemanden zum testen bzw. um zu schauen wo/wie die Daten herkommen brauchst, stehe ich gerne zur Verfügung
VG
Andreas

**Comment by simatec** [comment]
@fuxx-consulting Du kannst gerne die aktuelle Github Version testen.
Damit sollte es funktionieren

**Comment by fuxx-consulting** [comment]
@simatec Super. Es funktioniert sehr gut. morgen teste ich mal die lokale Anbindung
