### ISSUE TITLE
Solax adapter not refreshing data

### ISSUE THREAD

**Issue by louisvangeldrop** [simatec/ioBroker.solax#102]
The adapter connects to the pocket Wifi and collects the data only once after a restart of the adapter.
 
After the restart of the adapter, the adapter is not refreshing/polling the solax wifi pocket.

Admin version used: 6.0.7
Solax adapter version: 0.4.6

**Comment by Johan219** [comment]
Unfortunately, I am experiencing the same problem. Data from the solar panels is no longer updated. I have tried both API cloud and advanced settings through the wifi stick. 

I am using the latest version of the adapter. I have tried to reinstall the adapter a few times. After installation, the data is grabbed, but that's it. There is no updating.

**Comment by simatec** [comment]
Please post the debug log of the API request or the Wifi query

**Comment by louisvangeldrop** [comment]
There is no debug message in the "Logs"-tab from the Solax Adapter.

**Comment by simatec** [comment]
You need to set the adapter instance to debug

**Comment by louisvangeldrop** [comment]
solax.0 | 2022-06-24 13:21:01.578 | debug | Local Request Interval started ...
-- | -- | -- | --
solax.0 | 2022-06-24 13:21:01.576 | debug | Request Interval: 10 seconds
solax.0 | 2022-06-24 13:21:01.518 | debug | Sun Azimut: 170.6°
solax.0 | 2022-06-24 13:21:01.518 | debug | Sun Altitude: 61.7°
solax.0 | 2022-06-24 13:21:01.516 | debug | calculate astrodata ...
solax.0 | 2022-06-24 13:21:01.514 | debug | current local Time: 13:21
solax.0 | 2022-06-24 13:21:01.513 | debug | nauticalDawn: 03:20
solax.0 | 2022-06-24 13:21:01.512 | debug | nauticalDusk: 00:01
solax.0 | 2022-06-24 13:21:01.508 | debug | nightCalc started ...
solax.0 | 2022-06-24 13:21:01.506 | debug | System longitude: 5.606619 System latitude: 51.4393085
solax.0 | 2022-06-24 13:21:01.497 | debug | Solax is started in local-mode
solax.0 | 2022-06-24 13:20:59.134 | info | starting. Version 0.4.6 in /opt/iobroker/node_modules/iobroker.solax, node: v16.15.1, js-controller: 4.0.23

**Comment by simatec** [comment]
which firmware version is on your wifi stick?  Is the cloud connection working?

**Comment by louisvangeldrop** [comment]
Firmware version: 2.033.20
The cloud connection is working using my own software implementation in JS.

**Comment by simatec** [comment]
Please post the Config from the Adapter and the Wifi Stick

**Comment by Johan219** [comment]
If I can help, just let me know

**Comment by louisvangeldrop** [comment]
You are welcome to help.

**Comment by simatec** [comment]
@louisvangeldrop  If you have access to the Wifi Stick, please post the settings

**Comment by Johan219** [comment]
Here is my debug log

2022-06-24 23:38:46.474  - debug: solax.0 (14966) Solax is started in local-mode
--
2022-06-24 23:38:46.477  - debug: solax.0 (14966) System longitude: 6.17887272535988 System latitude: 52.4028345
2022-06-24 23:38:46.478  - debug: solax.0 (14966) nightCalc started ...
2022-06-24 23:38:46.478  - debug: solax.0 (14966) nauticalDusk: 00:14
2022-06-24 23:38:46.479  - debug: solax.0 (14966) nauticalDawn: 03:02
2022-06-24 23:38:46.479  - debug: solax.0 (14966) current local Time: 23:38
2022-06-24 23:38:46.479  - debug: solax.0 (14966) calculate astrodata ...
2022-06-24 23:38:46.480  - debug: solax.0 (14966) Sun Altitude: -9.8°
2022-06-24 23:38:46.480  - debug: solax.0 (14966) Sun Azimut: 332.4°
2022-06-24 23:38:46.541  - debug: solax.0 (14966) Request Interval: 10 seconds
2022-06-24 23:38:46.541  - debug: solax.0 (14966) Local Request Interval started ...

**Comment by Johan219** [comment]
I am also using firmware version: 2.033.20

**Comment by Johan219** [comment]
![Solax](https://user-images.githubusercontent.com/59110584/175697459-b75e89ca-9178-4348-8f35-0186e2efe420.png)

**Comment by Johan219** [comment]
![Wifistick 1](https://user-images.githubusercontent.com/59110584/175698296-890f2ac4-a482-4f70-8fd6-ce27d9f2714d.png)
![Wifistick 2](https://user-images.githubusercontent.com/59110584/175698297-7d8e2839-1c0a-4060-8e8c-7007d81e9e55.png)
![Wifistick 3](https://user-images.githubusercontent.com/59110584/175698298-cb31ce8c-0c28-4f3e-b13e-ac63bd056fc6.png)

**Comment by louisvangeldrop** [comment]
Wifi-stick System page

DHCP Static IP System
Firmware Version: 2.033.20
MAC address: D0-BA-E4-39-07-6E
SN: SWJVGXVXPP
IP address: 192.168.0.86
SSID: myssid
 Find AP
Key: Unhide
save
Select language: English

**Comment by Johan219** [comment]
@louisvangeldrop  @simatec The adapter is working again, data is being refreshed

**Comment by simatec** [comment]
Thx for your Feedback
