### ISSUE TITLE
I can't downgrade 

### ISSUE THREAD

**Issue by nykroy** [simatec/ioBroker.solax#117]
**Describe the bug**  
I tried to downgrade my pocket WiFi V2 versión 3.001.002 but It failed 
![Screenshot_20220917-113723_Brave](https://user-images.githubusercontent.com/7745881/190850491-3c9956ad-f58d-4acc-8162-fac104935998.png)

**To Reproduce**  

**Expected behavior**  

**Screenshots & Logfiles**  

**Versions:**  
 
![image](https://user-images.githubusercontent.com/7745881/190850924-c9944f13-31db-4c56-9d7e-f00bd6ccc2a0.png)

![Screenshot_20220917-114130_Brave](https://user-images.githubusercontent.com/7745881/190850638-e5fb5346-f1fa-4f21-b93a-10384f76f769.png)

**Additional context**

**Comment by simatec** [comment]
why a downgrade?  The version should fit.

**Comment by nykroy** [comment]
I tried to upload the .usb that you add to GitHub for access to the local data from x1 booster but this is is the response. I understand that I need downgrade with this file for access the data from inversor. Is not right?

**Comment by simatec** [comment]
your stick already has the v3 and should be suitable.  This is described in the documentation

**Comment by simatec** [comment]
The documentation states that the firmware for Wifi V3 must not be less than 3.001.
