### ISSUE TITLE
Status Icon

### ISSUE THREAD

**Issue by Charlie-2222** [simatec/ioBroker.solax#138]
Das Status Icon in der Ansicht Instanzen bleibt immer grün (Aktiv und Lebenszeichen) auch wenn keine Verbindung zum Solax WIFI Adapter besteht (Adapter wurde auch schon ausgesteckt)
Hier wäre eine genauere farbliche Statusanzeige hilfreich

**Comment by simatec** [comment]
Ist nicht geplant ...
