### ISSUE TITLE
Negative data values are not updated

### ISSUE THREAD

**Issue by tyler123durden** [simatec/ioBroker.solax#139]
At cloud mode negative data values seem to get not updated. For me feedinpower was not updated. 
I have added following line to: 
https://github.com/simatec/ioBroker.solax/blob/master/main.js
Line 274:
`await adapter.setStateAsync('data.feedinpower', solaxRequest.data.result.feedinpower ? solaxRequest.data.result.feedinpower : 0, true);`

Or remove the less equal zero check at line 315
`state.val >= 0`

Both fixes work for me, but I have no clue of any side affects or how this is intended to work, so hopefully you could find a proper solution. 

cheers, 
Thomas

**Comment by simatec** [comment]
Fix in v0.6.0
