### ISSUE TITLE
Issue + Solution for ioBroker (showing the wrong value for batpower)

### ISSUE THREAD

**Issue by jamakr4** [simatec/ioBroker.solax#166]
The probleme that I was facing is that the solax adapter reads out the wrong value for "batpower". When the value is actually =0.0 it does not write it in the batpower datapoint. Instead it just remains on the previous value which for my specific need is an issue because as I am doing a full visualisation, it shows the wrong value and with that beeing the case it also triggers the wrong animation in my vis. 

I fixed it by writting a Blokly script in the ioBroker that triggers every 10 seconds and if the soc (state of charge) of the Battery is =100 it just changes the value of the datapoint to 0 (You also need to allow "Writable" for batpower to work).

Not really sure why this happens maybe it is because I am using it with a Qcells system instead of a Solax one but the rest just works perfectly. BTW Solax and Qcells kind of belong together so the adapter is cross compatible to qcells in case you didnt know.

![Unbenannt](https://user-images.githubusercontent.com/68536642/236698242-0d94b29c-61a1-488a-8594-b6d95ee4d57b.PNG)

**Comment by simatec** [comment]
Cloud or local?

**Comment by jamakr4** [comment]
Cloud I think

**Comment by simatec** [comment]
You think or are you sure?
I needed this information a little more precisely...

**Comment by simatec** [comment]
Fix in v0.7.5
