### ISSUE TITLE
History Daten werden zu spät kopiert

### ISSUE THREAD

**Issue by erwini** [simatec/ioBroker.solax#174]
**Describe the bug**  
Die History Daten werden exakt 2 Stunde zu spät ausgelesen und geschrieben.

**Expected behavior**  
Die Daten sollten um 23:59:50 gelesen werden

Das sieht nach einem Zeitzonenproblem aus. Wie und wo kann man das beeinflussen? Einstellung am Adapter selber habe ich keine gefunden.

**Comment by simatec** [comment]
Da musst du dein Betriebssystem prüfen

**Comment by erwini** [comment]
date auf der linux cli gibt mir die aktuelle Zeit korrekt in UTC wieder, also -2h zur lokalen CEST ...

**Comment by simatec** [comment]
Naja das ist ja nicht korrekt... es sollte dir die lokale Zeit ausgeben. Also musst du sie anpassen

**Comment by erwini** [comment]
Linux auf lokale Zeitzone umgestellt und Adapter restartet. Funktioniert.
