### ISSUE TITLE
Solax X3 Hybrid - weitere Werte gefunden

### ISSUE THREAD

**Issue by Horstelix** [simatec/ioBroker.solax#179]
Servus,

ich habe noch ein  paar weitere Werte gefunden, die in den Adapter übernommen werden könnten:

Höchste und niedrigste Spannung der Zellen im Akku
Nr. 125  BatteryCellVoltage_max       Units.V          div100
Nr. 126  BatteryCellVoltage_min        Units.V          div100

Höchste und niedrigste Temperatur der Zellen im Akku
Nr. 112  BatteryCellTemperature_max      Units.C      div10
Nr. 113  BatteryCellTemperature_min       Units.C      div10

**Comment by simatec** [comment]
In der nächsten Version hinzugefügt
