### ISSUE TITLE
Adapter verliert Cloud Verbindung

### ISSUE THREAD

**Issue by cdaerr** [simatec/ioBroker.solax#183]
Heute morgen gegen 3:30 hat der Adapter die Verbindung zur SolaX Cloud verloren.
Der direkte Aufruf der API URL, so wie sie in der SolaX Cloud beschrieben wir funktioniert einwandfrei.

Eine Umstelelung des Loglevel auf debug zeigte folgendes:
![grafik](https://github.com/simatec/ioBroker.solax/assets/98185044/37610e60-1a8d-416d-8010-c2ef77887f53)

**Versions:**  
 - Adapter version: 0.7.7
 - JS-Controller version: 5.0.12
 - Node version: v16.20.2
 - Operating system: linux

**Comment by simatec** [comment]
Dann war sicher die Cloud nicht erreichbar .. Da kann der Adapter dann leider nichts machen

**Comment by cdaerr** [comment]
Nein, Cloud ist sowohl über App als auch API URL erreichbar.

Problem hat nur der Adapter. 


Am 10. November 2023 09:28:49 MEZ schrieb simatec ***@***.***>:

**Comment by simatec** [comment]
Welche URL verwendest du für den API Abruf?

**Comment by cdaerr** [comment]
Steht in der Fehlerbeschreibung:

Die API, wie in der SolaX Cloud beschrieben mit Key und Seriennummer. 


Am 10. November 2023 09:40:16 MEZ schrieb simatec ***@***.***>:

**Comment by cdaerr** [comment]
![grafik](https://github.com/simatec/ioBroker.solax/assets/98185044/d039d649-ab30-4c08-938c-0cbfbe275af7)

You see it works. It is not a problem of SolaX Cloud

**Comment by simatec** [comment]
Teste mal bitte folgende URL

`https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=xxxxxxxx&sn=xxxxxxxx`

**Comment by cdaerr** [comment]
Timeout:
![grafik](https://github.com/simatec/ioBroker.solax/assets/98185044/8bbd1e02-319f-4c11-a97d-eff2da336c49)

**Comment by simatec** [comment]
Dann hast du die Lösung ... Der Adapter verwendet diese URL ...

**Comment by simatec** [comment]
Mein Vorschlag ... teste mal die lokale Verbindung ... Die bringt am ende wesentlich mehr

**Comment by simatec** [comment]
> steht eigentlich alles in der Fehlerbeschreibung

da stand keine URL

**Comment by cdaerr** [comment]
Habe einen LAN Donlge, keinen WLAN Dongle, der unterstützt keine Lokale Verbindung.

**Comment by cdaerr** [comment]
> > steht eigentlich alles in der Fehlerbeschreibung
> 
> da stand keine URL

Es ist die URL, die du bekommst, wenn du dich in deinem Cloud Konto einloggst. Also die "offizielle"

**Comment by Matt77CHE** [comment]
Also bei mir ist das Selbe Problem, verwende den WLAN-Dongle.

**Comment by cdaerr** [comment]
Ja, bei mir auch. Der Zugriff über Port 9443 funktioniert auch wieder, auch wenn es nicht die "offizielle" URL für den API Zugriff ist.

**Comment by simatec** [comment]
> Vielleicht wäre aber eine Umstellung auf die in der Cloud angegebene URL aber trotzdem sinnvoll?

Der Wechsel fand stand, da die offizielle URL oft Timeouts hatte

**Comment by Matt77CHE** [comment]
Ok - bin soweit gekommen, dass ich auf das Web-Interface Zugriff habe - meiner Version ist 3.001.02 und wenn ich versuche das Downgrade zu machen, bekomme ich ein fail und er bleibt auf der 3.001.02
