### ISSUE TITLE
additional data for Solax X3 Hybrid G3, when using a second inverter and a second meter

### ISSUE THREAD

**Issue by winampdevil** [simatec/ioBroker.solax#186]
hello, 

i'm using a second inverter with a second DTSU-666-meter. 
The solax-adapter in cloud-mode report the power of this inverter as `feedinpowerM2` (see log)

solaxRequest: {"success":true,"exception":"Query success!","result":{"inverterSN":"xXxXxXxXxXxX","sn":"xXxXxXxXxXxX","yieldtoday":0.7,"yieldtotal":5160.7,"feedinpower":-564,"feedinenergy":5579.32,"consumeenergy":1942.26,"feedinpowerM2":-8,"soc":10,"inverterType":"5","inverterStatus":"109","uploadTime":"2023-12-23 21:27:52","batStatus":"0"},"code":0}

In local-mode, this data is at position 100 (value: -8, see log). The unit is "Watt".
(The value is negative, because this is the standby-power of the inverter at night.)

 {"type":"X3-Hybiyd-G3","SN":"xXxXxXxXxXxX","ver":"2.033.20","Data":[0,0,0,0,0,0,0,0,0.7,5160.7,-571,0,0,0,0,0,23,0.9,0,1385,0,10,216,174,25,25,17,16,3.1,3,165,1,0,0,0,0,0,0,0,0,0,5579.32,1942.18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,1,1,1,900,100,10,20,25,0,0,0,0,443.4,1818.2,5568.3,0,0,2,0,0,0,0,0,0,0,0,0,1,1,1,-8,1185.49,17.29,1,273,190.6,0,0],"Information":[6,5,"X3-Hybiyd-G3","xXxXxXxXxXxX",1,4.71,0,4.53,1.07],"battery":{"brand":"1","masterVer":"5.06","slaveNum":"4","slaveVer":[0,0,0,0,0,0,0,0],"slaveType":[0,0,0,0,0,0,0,0]}}

Is it possible, to integrate this value in a future version of the adapter?
Thank you
Frank

**Comment by simatec** [comment]
Fix in the next Version
