### ISSUE TITLE
Version 0.9.0 - zusätzliche Werte

### ISSUE THREAD

**Issue by Horstelix** [simatec/ioBroker.solax#187]
Hallo,

ich hab die neue Version ausprobiert, funktioniert einwandfrei.

Zwei Kleinigkeiten sind mir aufgefallen:
- bei  "batteryCellVoltageMin" wird als Name "Battery Cell Voltage Max" angezeigt.
- bei den Spannungswerten werden 3x,xx Volt angezeigt, richtig wären 3,xxx Volt. Wenn möglich, diese Werte bitte mit 3 Nachkommastellen anzeigen lassen.

**Comment by simatec** [comment]
> * bei den Spannungswerten werden 3x,xx Volt angezeigt, richtig wären 3,xxx Volt. Wenn möglich, diese Werte bitte mit 3 Nachkommastellen anzeigen lassen.

Ich habe es in Version 0.9.1 gefixt. Dann stimmen aber die Wete mit Div100 in deinem Issue nicht.
Musste nun div1000 setzen.
https://github.com/simatec/ioBroker.solax/issues/179#issue-1965430562

Prüfe das bitte nochmal zur Sicherheit...
