### ISSUE TITLE
Wallbox integration error: "Cannot read properties of undefined (reading 'name')" 

### ISSUE THREAD

**Issue by Azrael4224** [simatec/ioBroker.solax#188]
**Describe the bug**  
Hallo!

Vielen Dank für die Wallbox Integration, leider schlägt nach dem Update der Instanzstart fehl. Folgende Logs werden geschrieben:

`
solax.1 | 2024-01-02 10:26:29.394 | error | Cannot read properties of undefined (reading 'name')
solax.1 | 2024-01-02 10:26:29.393 | error | TypeError: Cannot read properties of undefined (reading 'name') at /opt/iobroker/node_modules/iobroker.solax/main.js:608:71
solax.1 | 2024-01-02 10:26:29.387 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'name')
solax.1 | 2024-01-02 10:26:29.386 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

Die Verbindung zu Wechselrichter bleibt bestehen und fragt auch weiterhin die Werte ab.

Screenshots:
Version 0.9.0:
![image](https://github.com/simatec/ioBroker.solax/assets/50657264/90d59a97-bc2f-43c4-b22b-7ef3f4105f74)

Log:
![image](https://github.com/simatec/ioBroker.solax/assets/50657264/fd7688a3-9556-468b-b331-2e04094856c0)

Nach downgrade auf Version 0.8.0:
![image](https://github.com/simatec/ioBroker.solax/assets/50657264/6cfddab9-de3f-4d2a-ad1c-7d13e04c47c4)

Systeminfo:
CPU: 8,2 %
RAM: 70 %
Betriebszeit: 6h
Verfügbar: 5.0.17
Installiert: 5.0.17
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 872 MHz
Modell: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
RAM: 3.7 GB
System-Betriebszeit: 05:47:33
Node.js: v18.19.0
NPM: 10.2.3
Adapter-Anzahl: 615
Datenträgergröße: 50.1 GB
Freier Festplattenspeicher: 32.9 GB
Aktive Instanzen: 22

**Comment by simatec** [comment]
Fix in v0.9.1
