### ISSUE TITLE
Solax adapter version 0.9.9 - incomplete data

### ISSUE THREAD

**Issue by Sansibari** [simatec/ioBroker.solax#206]
**Describe the bug**  

I have just set up the Solax adapter version 0.9.9 in a test environment.
I noticed that the adapter in "non-expert" mode no longer writes all data to the object database, even though this data is provided by the API.

Currently only the following "data" objects  are available:

<img width="1011" alt="Screenshot 2024-07-23 at 20 37 15" src="https://github.com/user-attachments/assets/2a5cd83d-9d6d-4dc4-984b-f181cf0b3449">

solax.0 info	State value to set for "solax.0.data.json" has to be type "string" but received type "number"
solax.0 warn	State "solax.0.data.yieldtotal" has no existing object, this might lead to an error in future versions
solax.0 info	starting. Version 0.9.9 in /opt/iobroker/node_modules/iobroker.solax, node: v18.20.2, js-controller: 5.0.19

**Versions:**  
 - Adapter version: <adapter-version>
      Version 0.9.9 in /opt/iobroker/node_modules/iobroker.solax, node: v18.20.2, js-controller: 5.0.19

 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by simatec** [comment]
This was already fixed a few versions ago.
Please delete the states and restart the adapter
