### ISSUE TITLE
Keine Daten nach Setup: Nicht verbunden mit Gerät oder Dienst

### ISSUE THREAD

**Issue by ph1ppm** [simatec/ioBroker.solax#217]
**Describe the bug**  
Credentials werden im Adapter hinzugefügt: API-Key (in App und Cloud identisch) + Seriennummer SN des Pocket-WLAN, aber testweise auch aller anderen Komponenten (WR und Datahub1000) erfolglos ausprobiert.
Verbindung laut obejct connected = false, somit keine Daten verfügbar.
Logfile anbei.

**Screenshots & Logfiles**  
[log.txt](https://github.com/user-attachments/files/17957796/log.txt)
![objects](https://github.com/user-attachments/assets/ee002f1f-1d10-4fe8-92a9-8bc4e729d089)
![status](https://github.com/user-attachments/assets/5c918425-9247-4975-81d5-d8e150bf77bd)

**Versions:**  
 - Adapter version: v0.9.12
 - JS-Controller version: 6.0.11
 - Node version: v18.19.1

**Comment by simatec** [comment]
Auch hier bitte die Config als JSON File und den debuglog von Solax posten

**Comment by ph1ppm** [comment]
[debug.txt](https://github.com/user-attachments/files/18097516/debug.txt)
[solax.admin_jsonConfig.json](https://github.com/user-attachments/files/18097837/solax.admin_jsonConfig.json)

**Comment by simatec** [comment]
Bitte deine Config als JSON File posten und nicht die jsonConfig.json

**Comment by ph1ppm** [comment]
Wo genau finde ich die?

**Comment by simatec** [comment]
Du kannst die Konfiguration im Menü vom Solax Adapter über die Pfeile oben rechts runterladen

**Comment by ph1ppm** [comment]
Danke für den Hinweis, hier die Config. Ich hab meine SN und den Token mal unkenntlich gemacht...

[solax.0.json](https://github.com/user-attachments/files/18109774/solax.0.json)

**Comment by simatec** [comment]
Bitte teste folgende URL über den Browser:

https://www.eu.solaxcloud.com/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=xxxxxx&sn=xxxxxx

**Comment by ph1ppm** [comment]
Fehlermeldung beim Aufruf der URL:
{"exception":"token invalid!","code":103,"tokenId":"xxxxxx","success":false}

Token und SN natürlich vorher eingesetzt.
Ich hab auch nochmal den Token im Webinterface der Solax Cloud abgeglichen und er ist definitiv korrekt.

**//Update**: Neugenerierung des Tokens bringt die Instanz jetzt zum fliegen... keine Ahnung, warum es mit dem Vorherigen nicht geklappt hat.
